# Generated by Django 3.1.5 on 2024-02-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0002_ltcform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTCform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('block_year', models.CharField(max_length=100, null=True)),
                ('pf_no', models.IntegerField(max_length=22, null=True)),
                ('basic_pay_salary', models.IntegerField(max_length=10, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('department_info', models.CharField(max_length=20, null=True)),
                ('leave_availability', models.BooleanField(default=False)),
                ('leave_start_date', models.DateField(blank=True, max_length=6, null=True)),
                ('leave_end_date', models.DateField(blank=True, max_length=6, null=True)),
                ('date_of_leave_for_family', models.DateField(blank=True, max_length=6, null=True)),
                ('nature_of_leave', models.TextField(null=True)),
                ('purpose_of_leave', models.TextField(null=True)),
                ('hometown_or_not', models.BooleanField(default=False, null=True)),
                ('place_of_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('address_during_leave', models.TextField(null=True)),
                ('mode_for_vacation', models.BooleanField(null=True)),
                ('details_of_family_members_already_done', models.TextField(null=True)),
                ('family_members_about_to_avail', models.CharField(max_length=100, null=True)),
                ('details_of_family_members', models.TextField(null=True)),
                ('details_of_dependents', models.TextField(null=True)),
                ('amount_of_advance_required', models.IntegerField(blank=True, null=True)),
                ('certified_family_dependents', models.TextField(null=True)),
                ('certified_advance', models.TextField(null=True)),
                ('adjusted_month', models.TextField(null=True)),
                ('date', models.DateField(max_length=6, null=True)),
                ('phone_number_for_contact', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
