# Generated by Django 3.1.5 on 2024-02-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0003_auto_20240218_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltcform',
            name='employee_id',
            field=models.IntegerField(default=5318, max_length=22),
            preserve_default=False,
        ),
    ]
