# Generated by Django 3.1.5 on 2024-02-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0004_ltcform_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltcform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
