# Generated by Django 3.1.5 on 2024-02-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0005_auto_20240219_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltcform',
            name='details_of_family_members',
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='adjusted_month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='basic_pay_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='block_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='certified_advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='date_of_leave_for_family',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='employee_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='hometown_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='leave_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='mode_for_vacation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='pf_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='phone_number_for_contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
