# Generated by Django 3.1.5 on 2024-03-18 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20240314_0030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr2', '0007_auto_20240314_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appraisal_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpdaadvanceform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPDA_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpdareimbursementform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPDAR_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leave_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ltcform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LTC_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appraisal_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cpdaadvanceform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPDA_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cpdareimbursementform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPDAR_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leave_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ltcform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LTC_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_leave', models.IntegerField(default=0)),
                ('hcl_leave', models.IntegerField(default=0)),
                ('el_leave', models.IntegerField(default=0)),
                ('vacation_leave', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
        ),
    ]
